version: '3.8'
services:
  backend:
    image: "unitmesh/chocolate-factory:latest"
    ports:
      - "18080:18080"
    environment:
      - OPENAI_API_KEY=""
      - OPENAI_API_HOST="https://api.openai.com/"
    networks:
      - dependence_network

  frontend:
    image: "unitmesh/chocolate-factory-frontend:latest"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_SERVER_URL="http://localhost:18080"
    networks:
      - dependence_network

networks:
  dependence_network:
