server:
  port: 18080
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    hikari:
      connection-timeout: 50000


# vector store config
store:
  pinecone:
    api-key: sk-xxx
    environment: dev
    project-id: xxx
    index: xxx
    name-space: xxx
