server:
  port: 18080
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    hikari:
      connection-timeout: 50000

# config in application-dev.yml
#openai:
#  api-host:
#  api-key:
